-- EX2 Part2


---- init:
ALTER TABLE CLIENTS 
ADD COLUMN BANKNAME VARCHAR(255);
UPDATE CLIENTS  SET BANKNAME = 'SPBERBANK' WHERE (ID = 1)OR(ID=3);
UPDATE CLIENTS  SET BANKNAME = 'TINKOFF' WHERE (ID = 2);
INSERT INTO CLIENTS (NAME,CREDIT) VALUES ('COMMITION',0.0);
COMMIT;

---- CODE:
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SAVEPOINT SP0;
UPDATE CLIENTS  SET CREDIT = CREDIT-500 WHERE (ID = 1);
UPDATE CLIENTS  SET CREDIT = CREDIT+500 WHERE (ID = 3);
UPDATE CLIENTS  SET CREDIT = CREDIT-0.0 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+0.0 WHERE (ID = 4);
SAVEPOINT SP1;
UPDATE CLIENTS  SET CREDIT = CREDIT-700 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+700 WHERE (ID = 1);
UPDATE CLIENTS  SET CREDIT = CREDIT-30 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+30 WHERE (ID = 4);
SAVEPOINT SP2;
UPDATE CLIENTS  SET CREDIT = CREDIT-100 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+100 WHERE (ID = 3);
UPDATE CLIENTS  SET CREDIT = CREDIT-30 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+30 WHERE (ID = 4);
SAVEPOINT SP3;

-- view data 
SELECT * FROM CLIENTS ORDER BY ID;

-- ROLLBACK 
ROLLBACK;

-- view data 
SELECT * FROM CLIENTS ORDER BY ID;
