-- CREATE TABLE LEDGER(
-- ID SERIAL UNIQUE NOT NULL,
-- FROM_ID INT references CLIENTS(ID),
-- TO_ID INT references CLIENTS(ID),
-- FEE FLOAT,
-- AMOUNT FLOAT,
-- TR_DATE TIMESTAMP
-- );

BEGIN TRANSACTION;

SAVEPOINT SP0;
UPDATE CLIENTS  SET CREDIT = CREDIT-500 WHERE (ID = 1);
UPDATE CLIENTS  SET CREDIT = CREDIT+500 WHERE (ID = 3);
UPDATE CLIENTS  SET CREDIT = CREDIT-0.0 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+0.0 WHERE (ID = 4);
INSERT INTO LEDGER(FROM_ID,TO_ID,FEE,AMOUNT,TR_DATE) 
VALUES(1,3,0,500,CURRENT_TIMESTAMP);
SAVEPOINT SP1;
UPDATE CLIENTS  SET CREDIT = CREDIT-700 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+700 WHERE (ID = 1);
UPDATE CLIENTS  SET CREDIT = CREDIT-30 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+30 WHERE (ID = 4);
INSERT INTO LEDGER(FROM_ID,TO_ID,FEE,AMOUNT,TR_DATE) 
VALUES (2,1,30,500,CURRENT_TIMESTAMP);
SAVEPOINT SP2;
UPDATE CLIENTS  SET CREDIT = CREDIT-100 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+100 WHERE (ID = 3);
UPDATE CLIENTS  SET CREDIT = CREDIT-30 WHERE (ID = 2);
UPDATE CLIENTS  SET CREDIT = CREDIT+30 WHERE (ID = 4);
INSERT INTO LEDGER(FROM_ID,TO_ID,FEE,AMOUNT,TR_DATE) 
VALUES (2,3,0,100,CURRENT_TIMESTAMP);
SAVEPOINT SP3;

COMMIT TRANSACTION;
